### ISSUE TITLE
REST backend: inconsistency with trailing dot

### ISSUE THREAD

**Issue by j-vizcaino** [theforeman/smart_proxy_dns_powerdns#35]
### Environment

* SmartProxy 1.13.3
* Plugin version 0.3.0
* PowerDNS 3.4.7 with API backend enabled

### Description

I am unable to add new records because the plugin cannot find the zone associated with the new host.
It seems this is related to the trailing dot added to the fqdn when looking for the zone.

When queried with the JSON API, PowerDNS returns a zone that looks like this:

```json
{
  "id": "example.com.",
  "url": "/servers/localhost/zones/example.com.",
  "name": "example.com",
  "kind": "Master"
}
```

Note the trailing dot is missing from the name but present in the id field.
Therefore, I think the `zone["id"]` should be used in `get_zone` and not `zone["name"]`

**Comment by ekohl** [comment]
This is a known issue. The PDNS 3.x API is experimental and differs from the PDNS 4.x API. Most notably the URLs and the trailing dots were added (and are required for the input as well). So even when ```get_zone``` would fine the zone, I think the creation would fail.

Supporting the v0 API isn't all that hard (my initial REST implementation was written against it), but given the 3.4.x to 4.x upgrade should be relatively painless (since there is no schema change) I'm wondering if it's worth to support the v0 API. The biggest issue I see with it is that I'd like to avoid as much configuration as possible. Maybe the README should be more explicit in that only the v1 API is supported and the v0 API is known to be broken.

What are your thoughts on this?

**Comment by j-vizcaino** [comment]
That makes sense: adding a note to the README would be a must since I wasted nearly 2 hours figuring out why my configuration was not working :(
Maybe it's time for me to upgrade to PDNS 4.

**Comment by ekohl** [comment]
I've gone ahead and make it explicit in the README. I'd still be open to a patch to support v0, but I would preferred if everyone is on PDNS 4 :)
